name: Workflow Test With Runner

run-name: Workflow Test With Runner

on:
    - push

jobs:
    Testing:
        runs-on: self-hosted
        steps:
            - name: Spin it up
              run: echo "building......."
            - name: Get code
              uses: actions/checkout@v4
            - name: List files
              run: |
                ls ${{github.workspace}}
